param(
    [switch]$EmitEnvToStdout
)

$ErrorActionPreference = 'Stop'

$CertSubject = 'CN=DS E Test Signing'
$CertFriendlyName = 'DSE Test Signing'
$CertEKU = '1.3.6.1.5.5.7.3.3'
$OutPfxRelative = 'release\certs\dse_signing.pfx'
$OutSecrets = '.github\dse_signing_secrets_generated.env'

# Ensure output directory
$OutPfxPath = Join-Path (Get-Location) $OutPfxRelative
$OutPfxDir = Split-Path $OutPfxPath -Parent
if (-not (Test-Path $OutPfxDir)) { New-Item -ItemType Directory -Path $OutPfxDir | Out-Null }

# Generate a random password (32 bytes -> base64 string)
$bytes = New-Object byte[] 32
$rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::Create()
$rng.GetBytes($bytes)
$RandomPassword = [System.Convert]::ToBase64String($bytes)

Write-Host "Generated random password (length $($RandomPassword.Length)): [hidden]"

# Remove any existing cert with same subject in CurrentUser\My
$existing = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -eq $CertSubject }
if ($existing) {
    Write-Host "Removing existing certificate with subject $CertSubject"
    foreach ($c in $existing) { Remove-Item -Path "Cert:\CurrentUser\My\$($c.Thumbprint)" -Force }
}

# Create the self-signed certificate
Write-Host "Creating self-signed certificate for $CertSubject"
$cert = New-SelfSignedCertificate -Subject $CertSubject -CertStoreLocation Cert:\CurrentUser\My -KeyUsage DigitalSignature -Type CodeSigning -FriendlyName $CertFriendlyName -NotAfter (Get-Date).AddYears(20) -TextExtension @("2.5.29.37={text}$CertEKU") -KeyExportPolicy Exportable

# Export to PFX
if (Test-Path $OutPfxPath) { Remove-Item $OutPfxPath -Force }
$securePwd = ConvertTo-SecureString -String $RandomPassword -Force -AsPlainText
Write-Host "Exporting PFX to $OutPfxPath"
Export-PfxCertificate -Cert $cert -FilePath $OutPfxPath -Password $securePwd | Out-Null

# Base64 encode PFX
[byte[]]$pfxBytes = [System.IO.File]::ReadAllBytes($OutPfxPath)
$pfxBase64 = [System.Convert]::ToBase64String($pfxBytes)
if ($EmitEnvToStdout) {
    # Emit env-style lines to stdout so caller can capture them in-memory
    Write-Output "SIGNING_PFX=$pfxBase64"
    Write-Output "SIGNING_PASSWORD=$RandomPassword"
    Write-Output "PFX_PATH=$OutPfxPath"
} else {
    # Write secrets file
    $envContents = @()
    $envContents += "# Generated by .github/scripts/generate_pfx.ps1"
    $envContents += "# WARNING: treat this file like a secret and do not commit to public repos"
    $envContents += "SIGNING_PFX=$pfxBase64"
    $envContents += "SIGNING_PASSWORD=$RandomPassword"

    Write-Host "Writing secrets to $OutSecrets"
    Set-Content -Path $OutSecrets -Value ($envContents -join "`n") -Encoding ASCII

    Write-Host "Done. Secrets written to $OutSecrets and PFX saved to $OutPfxPath"
    Write-Host "To set repository secrets, copy values from $OutSecrets into your repo Settings -> Secrets -> Actions"
}
