[dse]
; Automatically toggle DSE. If DSE was already disabled
; patcher will not run.
toggleDse=true

; Enable/disable Steam API hooks
steamHooks=false

; Enable/disable logging output
logging=false

; Its dependent on toggleDse
; Problematic services to stop or delete (Format: ServiceName:ACTION)
; STOP - just stops the service, and relaunches once game ends
; DELETE - deletes the service, and does not relaunch
problematic_services=vgk:STOP, vgc:STOP, FACEIT:DELETE

; Problematic tasks to kill (comma separated executable names, these are not relaunched)
problematic_tasks=vgtray.exe,
