[dse]
; Automatically toggle DSE. If DSE was already disabled
; Drvloader will not run.
toggleDse=true

; Enable/disable Steam API hooks
steamHooks=false

; Enable/disable logging output
logging=false
