[dse]
; Auto dse toggle (NOTE: if dse was off before kvc wont run)
toggleDse=true

; Appends --safe to all kvc commands
dseSafeMode=true

; Enable/disable Steam API hooks
steamHooks=false

; Enable/disable logging output
logging=false
